### ISSUE TITLE
ObjectHash work with move in Array

### ISSUE THREAD

**Issue by desireezhu** [benjamine/jsondiffpatch#111]
Hello Benjamine,

I suppose following delta would be undefined (ignore move in Array) but not work as expected. Did I do something wrong?

var jsondiff = require('jsondiffpatch').create({
    objectHash: function(obj){
        return obj.sampleid;
    },
    arrays: {
        detectMove: false
    }
});

var sampleArray1 = [{"sampleid":1}, {"sampleid":2}];
var sampleArray2 = [{"sampleid":2}, {"sampleid":1}];

var delta = jsondiff.diff(sampleArray1, sampleArray2);
console.log(delta);
_________________________________________________________
{ '0': [ { sampleid: 2 } ],
  _t: 'a',
  _1: [ { sampleid: 2 }, 0, 0 ] }

Thanks!

**Comment by benjamine** [comment]
I see, sorry but that's not exactly how the `detectMove` flag works (it might need better documentation),
the `detectMove` won't make diff ignore positions, instead "move detection" is a final step in the diff that finds matching remove+add operations and converts them into "moves", if you turn it off, you'll just have the remove + add (as you see in your example).
In your case I'd guess you might be better with move detection on, and then ignore/trim them (ie. any array with `3` in index 2: https://github.com/benjamine/jsondiffpatch/blob/master/docs/deltas.md#array-moves.

```
function ignoreArrayMoves(delta) {
  if (Array.isArray(delta) && delta[2] === 3) {
    return;
  }
  if (typeof delta !== 'object') {
    return delta;
  }
  var trimmed = Array.isArray(delta) ? [] : {};
  for (var key in delta) {
    trimmed[key] = ignoreArrayMoves(delta[key]);
  }  
  return trimmed;
}
console.log(ignoreArrayMoves(delta))
```

ps: it might be possible also, that if order is irrelevant, you could use an object with ids as keys, instead of an array?

**Comment by desireezhu** [comment]
thanks Benjamine, I see, please close this issue.
