### ISSUE TITLE
Showing diff for same objects

### ISSUE THREAD

**Issue by mimani** [benjamine/jsondiffpatch#122]
Hi,

I was testing this for one of my use-case, when I found while testing at this [link](http://benjamine.github.io/jsondiffpatch/demo/index.html):

Following object shows diff when compared to itself:

```
{
  "countries": [
    {
      "name": {  "ram": "Bolivia"},
      "independence": "1825-08-05T18:30:00.000Z",
      "unasur": true
    }
  ]
}
```

I get following in diff:

```
{	
  "countries": {	
    "_t": "a",	
Array delta (member names indicate array indices)
    "_0": {	
      [
  {
    "name": {
      "ram": "Bolivia"
    },
    "independence": "1825-08-05T18:30:00.000Z",
    "unasur": true
  },
  0,
  0
]	
remove index 0 ([previousValue, 0, 0])
    },	
    "0": {	
      [
  {
    "name": {
      "ram": "Bolivia"
    },
    "independence": "1825-08-05T18:30:00.000Z",
    "unasur": true
  }
]	
insert at index 0 ([newValue])
    }	
  }	
}
```

**Comment by benjamine** [comment]
that's because the demo page uses an `objectHash` function that uses `name` (if found) to match objects. In your example object `name` is an object, which will always be different to another instance (`!==`). ie. there's no way to tell the 2 objects in left and right arrays are the same (`===` returns false), unless you provide an objectHash function that match those objects:

``` js
var jdp = jsondiffpatch.create({
  objectHash: function(obj) {
     return obj.name.ram;
  }
]);
```

if you don't specify any `objectHash`, and objects are not `===`, it will fallback to match by position.

(from readme)
**IMPORTANT NOTE**: to match objects inside an array you must provide an objectHash function (this is how objects are matched, otherwise a dumb match by position is used). For more details, check Array diff documentation
