### ISSUE TITLE
jsondiffpatch fails creating a detla for an array where only the index changed

### ISSUE THREAD

**Issue by rvetere** [benjamine/jsondiffpatch#140]
Maybe it is correct behaviour but then i don't know how to deal with it.. my stories goes like this, i'm starting with a json document, defining rows and columns down to an array of widgets:

![fig1](https://photos-6.dropbox.com/t/2/AABM2ti00HUr91I8USoFOoUzRVHnSLbCnES0Au9IxOiPiA/12/4549844/png/32x32/3/1458237600/0/2/Screenshot%202016-03-17%2014.33.50.png/EPDXtAMYu-sTIAcoBw/LSIwXhjeud9HDRqi4SaF8GXMeGGoqNHOXmHdfEP0Gls?size_mode=5&size=32x32)

You can see, currently i'm having two widgets in the expanded column. Now i'm changing the order of those two widgets, the one on index 0 will become index 1, and vise versa.

So the modified json document will look like this:

![fig2](https://photos-4.dropbox.com/t/2/AACPKrdrCcx-fpDsrWn_f4QMhgEgnKbg2xYOSezAZoAemg/12/4549844/png/32x32/3/1458237600/0/2/Screenshot%202016-03-17%2014.39.08.png/EPDXtAMYvesTIAcoBw/CDrnbCE_Zutjne4eGm3J4VAq0KPGCDGN8cZs8ZZ5gdM?size_mode=3&size=1024x768)

Now i'm making a delta with jsondiffpatch, straight forward:

`var delta = jsondiffpatch.diff(this.documentData, modifiedJson);`

And now comes my confusion, the delta will generate a construct like this:

![fig3](https://photos-3.dropbox.com/t/2/AAAp6uoFahTaOoqVHRwY2n5pXZ-03WQgwcSg4qK_qFmReQ/12/4549844/png/32x32/3/1458237600/0/2/Screenshot%202016-03-17%2014.41.12.png/EPDXtAMYv-sTIAcoBw/RM20kmFwyFOyeruyG7mWGNTMRxhli3md89GfcvJRvek?size_mode=3&size=1024x768)

I thought he would just change the order of the widgets array - but instead he completely merged them together by changing my string field "content" into an array and pushing into it both variants...

I think, i can't be mad with jsondiffpatch because he simply doesn't know it better what to do (he doesn't know the interface or anything from my typescript definition to avoid this, and maybe he's not really able to solely detect the index change..?)

I don't want to complain "heeeey, new bug found!".. i'm not really sure if this is an actual issue.. well, for me and my app logic it is indeed, i totally don't know now how i should handle position changes in widgets and not ending by saving the complete document again rather than using the delta... 

Some toughts of the pros here how this could be solved/workarouneded?

**Comment by benjamine** [comment]
Hi, you're right, jsondiffpatch doesn't know how to match objects in both arrays (unless they were equal by reference), so when there's no better hint, it defaults to match by position (dumb, but ok for simple cases).
You can improve that if you provide an `objectHash` function to match these objects, eg. you can add an id field on those widget objects (or any function to obtain a unique identifier from an object), so there's a way to track movements.
Here's an example:
https://github.com/benjamine/jsondiffpatch/blob/master/docs/arrays.md#an-example-using-objecthash
that will give you the expected result (1 array move, instead of 2 item updates).

**Comment by rvetere** [comment]
Thanks for the clarification - so i will introduce an id field on my widgets with a unique-id and everything will work perfectly :)
