### ISSUE TITLE
Sparse Arrays

### ISSUE THREAD

**Issue by bvanheukelom** [benjamine/jsondiffpatch#157]
```
var jsondiffpatch = require("jsondiffpatch");

var a = [null,{"x":true}];
var b = [null,{"x":true}];

var diff1 = jsondiffpatch.diff(a,b);

console.log(diff1); // { '1': [ { x: true } ], _t: 'a', _1: [ { x: true }, 0, 0 ] }




var c = [{},{"x":true}];
var d = [{},{"x":true}];

var diff2 = jsondiffpatch.diff(c,d);

console.log(diff2); // undefined
```

Granted diff1 seems to have no effect when applied to an object these results still seem sort of inconsistent.

Thanks for the great library. Let me know what you think.

**Comment by benjamine** [comment]
hi @bvanheukelom , array diffing with nested objects is always complicated, but what you're seeing is expected behavior, figuring out how to match items in left and right arrays is not trivial, so jsondiffpatch does a few things to try guess the best way:
- if you provide a `jsondiffpatch.create({ objectHash: function(...){...});` it will use that, a typical case is `return obj.id`, which is what the demo page uses
- if you don't it will try to choose between 2 simple, but dumber, approaches:
  - if any pair of items are `===`, it will just match by `===` (and this is what happens in your case as `null === null`, ie jsondiffpatch assumes it can match items by value or ref equality (but unfortunately `{x: true} !=== {x: true}`.
  - otherwise it will fallback to just match by position, which is ok for many scenarios (in which items don't shuffle much inside the array), this is probably what you'll want for your example

if you didn't had those `null` values (or any matching by value items) in both sides, your example would work just fine, but luckily there's a way to force match by position: 

``` js
diffPatcher = jsondiffpatch.create({ matchByPosition: true });
console.log(diffPatcher.diff([null,{"x":true}], [null,{"x":true}]));
// logs "undefined"
```

**Comment by bvanheukelom** [comment]
Good morning Benjamine

Thank you for the very fast answer. I will update my usage of jsondiffpatch to include the parameters you've provided. Will this change anything about the semantics of its behaviour? I assume it will just decrease it's performance - which is not an issue in my scenario. Is that correct ?

Another thought:

If you gave a person the two jsons `[null,{"x":true}]` and `[null,{"x":true}]` and asked them whether those are the same they would surely respond with "yes, totally utterly the same. No difference can be found.". They would not think about javascript object equality and the difference between the `==` and the `===` operator. While I see that the internals of the library need to be considered the result is a bit unexpected. Why not make `matchByPosition : true` the default setting? My friend [Pola](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) nods wildly in support of this idea.

Well in any case. Thanks again for your contributions to the open source world. Really appreciate your work and my ramblings are really just "complaining on a high level".

Bert

**Comment by benjamine** [comment]
Thanks, no, it shouldn't affect performance, actually it might bring a little win, as you'd be telling jsondiffpatch not to try guessing.

re. the default yes, I know your friend Pola :), the only gotcha is there other scenarios in which Pola works the other way around, and it's not trivial to distinguish, ie. if you have this:

`diff( [1, 2, 3, 4, 5], [1, 5, 2, 3, 4])` matchByPosition will throw a very bad result (it will think everything after 1 changed), same for even a trivial insert in the middle of an array, while current behavior will realize match by `===` is possible, and output the expected, ie. "item `5` at index 4 moved to index 1".

perhaps the optimal result would be obtained trying both approaches and test which one gives the simplest delta, but that's too expensive. 
but I think maybe the method to guess if matchByPosition could change, eg.
currently match by `===` gets activated as soon as there's any `===` match across arrays, perhaps it should do that only if the match is between different positions, as otherwise matchByPosition may still be the best, thoughts?

**Comment by bvanheukelom** [comment]
Why not user structural equality instead of === ? The === operator is really the bad guy in this case. 

If that is too slow maybe [hash trees](https://en.wikipedia.org/wiki/Merkle_tree) could help.

**Comment by benjamine** [comment]
I think what you propose can be done now by providing an `objectHash` function in the options.
but that's not ok for the general case:
- it could be too expensive, hash trees are fast only after they're generated, I think that's what Immutable.js would give you, if you use Immutable.js, then `===` just works (super fast) with object trees (though diffing and patching Immutable.js objects it not supported yet, would require a plugin maybe), but that's not everyone.
- even more important, deep equality is not always a good approach for matching, if you use it, and you have only modified a part of the object inside of the array, deep equality would tell you it's a totally different object (generating a full remove+add), while matching by id or position would just diff inside the object (inside the array).

**Comment by bvanheukelom** [comment]
Alright. If hash trees are too expensive, than it's necessary to settle for something that's a faster and less precise. I guess my initial example falls under "making a compromise". Makes sense. 

Not sure I completely understand what "matching" really means but hash trees are better at comparing than === for this case I'd say. This is really where it would help. Keep all the good magic that decides what to compare with what but replace === with the hash comparison.

**Comment by benjamine** [comment]
it's not just the cost, it's also the 2nd point, matching means identified the "same" object in the 2 arrays, where "same" is something that depends on your domain, it could be that the 2 objects have the same `productId` (but some data inside might have changed):
`jsondiffpatch.create({ objectHash: obj => obj.productId });`.

if you prefer a deep comparison, because you're certain that the objects inside your arrays will never be modified, but only moved of position, and they don't have circular references, and they aren't very very deep, then, you can just `jsondiffpatch.create({ objectHash: obj => aHashLibrary(obj) });` (eg. https://www.npmjs.com/package/object-hash ) , maybe I can recommend one in the README, but I can't include it or make it the default.

I think I'll move to `matchByPosition` for the test case you provided, and that would create no diff. then if someone happens to move the objects in the array, and also includes other items that match by ref and also moved, well, it's a reasonable edge case that the default won't magically handle.

**Comment by bvanheukelom** [comment]
Hey Benjamine. Thank you for answering!

Sure, a user still remains able to add a objectHash function and thereby provide their own method of determining equality. Let's leave that aside as that should not change. 

You keep mentioning that the usage of the `===` operator OR `matchByPosition` is somehow integral to the ability to use the smart algorithm that figures out movements in an array. I understand you so that you're saying: If jsondiffpatch wouldnt use either  `===` OR `matchByPosition` (which is a more structural compare). Then that smartness of finding moves would not be possible. 

I think I would have to look into the code to see why that is the case. In my mind a hash tree is just a better version of the `===` operator.

In any case. Let's close this. The lib is fine the way it is. And it doesn't really matter how it does what it does.

Thank you again for the work and the support.

Bert

**Comment by benjamine** [comment]
ok, since `0.2.3` now `matchByPosition` is used by default unless a match by ref is found **between different indices** in left/right arrays. this means now the example you provided works as expected (no diff). thanks!
