### ISSUE TITLE
Questions about processing the deltas

### ISSUE THREAD

**Issue by wayne-o** [benjamine/jsondiffpatch#91]
Hi

Not sure if this is the best place to ask this but I've just started using this project in our import process and have a couple of things that aren't very clear to me:

1 - what's the best way of programatically testing each delta for it's type? For me i just want to create a task that acts on the difference so all additions, updates and deletions need to be gathered so I can work on them - so far i have this to test for an addition:

```if (current[1] === undefined && current[2] === undefined && !_.isString(current)) {```

But that seems very hacky! How does everyone else test for this?

2 - one of the nodes is ``` "_t": "a",``` and I think that implies the following node is an array change? This makes it quite hard when trying to loop through all the differences to process them - am I going about this wrong? Is there an approach I can use that means I don't loop through the differences to act on my data? 

To be more clear about our usage - The JSON I am diffing is only a skeleton representation we gather from another service - we use it to update our relational database. We store the JSON each time we update so we can diff against the previous one to find what has been updated.  So for each difference we find in the JSON files we have to create an update task to reflect these changes in our database.

Here is an output from my diff:

```
{
  "0": [
    {
      "name": "Pyramid",
      "events": [
        {
          "name": "N-Dubz Tribute Act",
          "short": "ndubzt(1)",
          "start": "2015-06-27 22:30",
          "end": "2015-06-28 00:00"
        },
        {
          "name": "Sex Pistols",
          "short": "spistol(1)",
          "start": "2015-06-27 22:30",
          "end": "2015-06-28 00:00"
        }
      ]
    }
  ],
  "1": [
    {
      "name": "Pyramid 2",
      "events": [
        {
          "name": "Act 1",
          "short": "a1(1)",
          "start": "2015-06-27 22:30",
          "end": "2015-06-28 00:00"
        },
        {
          "name": "Act 2",
          "short": "a2(1)",
          "start": "2015-06-27 22:30",
          "end": "2015-06-28 00:00"
        }
      ]
    }
  ],
  "_t": "a",
  "_0": [
    {
      "name": "Pyramid 3",
      "events": [
        {
          "name": "N-Dubz Tribute Act",
          "short": "ndubzt(1)",
          "start": "2015-06-27 22:30",
          "end": "2015-06-28 00:00"
        },
        {
          "name": "Sex Pistols",
          "short": "spistol(1)",
          "start": "2015-06-27 22:30",
          "end": "2015-06-28 00:00"
        }
      ]
    },
    0,
    0
  ]
}
```

**Comment by benjamine** [comment]
1- maybe this should migrate into the jsondiffpatch core, but here's the function you're looking for:

https://github.com/benjamine/jsondiffpatch/blob/master/src/formatters/base.js#L166

if you want to invoke that function you'll have to instantiate any formatter, eg. annotated one (you need to include the formatters bundle (or the jsondiffpatch-full one, which includes them)), and then you can do:

``` js
(new jsondiffpatch.formatters.annotated.AnnotatedFormatter()).getDeltaType(yourDelta)
```
(yes, I'll probably move that to something like `jsondiffpatch.getDeltaType` and use constants)

2- yes, `_t === 'a'` means the object being diffed/patched is an array (otherwise it's an object), I don't know if I understand the but, you don't need to loop to find that out, you can just start by asking `isArray === delta._t === 'a'`.
In any case, for understanding deltas you can always use the [DEMO page](http://benjamine.github.io/jsondiffpatch/demo/index.html) and click on "JSON (Annotated)", to see an the JSON annotated on each node explaining what they mean.

**Comment by olecom** [comment]
Hi. Let me ask about deltas too.

Why `no change` has `undefined` delta? This cannot be serialized into JSON, no?

Would it be more convenient if `{}` will be such case, so `0 === Object.keys(delta)`.
Thus maybe https://github.com/benjamine/jsondiffpatch/issues/128 wouldn't be ignored as a case.

**Comment by benjamine** [comment]
@olecom `JSON.stringify(undefined)` returns `undefined` (although you're right that's not a parseable JSON string), I think the intention was to let people do things like:
 ``` js
  if (!jsondiffpatch.diff(a, b)) {
    // a and b are equal
  }
```
(perhaps `null` could work fine there too, which does work for `JSON.parse`), and also make the result of .diff somewhat consistent recursively (ie. when 2 properties have no difference that property is not on the parent delta, ie. it's `undefined`).

the issue mentioned is more a bug in how the demo page displays unchanged values.

**Comment by olecom** [comment]
@benjamine 
> somewhat consistent recursively
Yes, it could.

But whole delta as an entity (which can be embedded into other JSON structures) and inner deltas are different things IMHO.

**Comment by olecom** [comment]
May i ask another question here about `about processing the deltas`. Thanks.

There are many issues opened on and on regarding Array diffing. But my question is:
if `objectHash` was used, how to recognize modified array items in delta itself?
or it would be very useful to have a delta syntax with `id` values to identify items, like:
```js
{
  _t: 'a',
  1: ['oldValue', 'newValue'],
  $1: 'SomeFancyId1'
}
```
`Added`, `moved` and `deleted` ones has options to include whole data object in, thus identification is possible.

**Comment by benjamine** [comment]
> if objectHash was used, how to recognize modified array items in delta itself?

it's by position, not everyone wants or needs ids in their array items.

> it would be very useful to have a delta syntax with id values to identify items

it would be possible to, optionally, always include a specific field in array deltas (like an id), perhaps for logging or conflict resolution (something this lib doesn't support, at least yet), is that what you intend?.
I don't remember any requests for that in the past. I assume in most cases if you have a collection where id is more important, and if you don't care about order, you can do better using an object map instead of an array.

**Comment by olecom** [comment]
> it would be possible to, optionally, always include a specific field in array deltas (like an id), perhaps for logging or conflict resolution (something this lib doesn't support, at least yet), is that what you intend?.

Yes.I need `id`s in delta just not to go into `right` object again and inspect some position.

**Comment by benjamine** [comment]
ok, you can do that by writing a plugin (probably you'll need to look into the internal of the diff code (pipe and filters) to understand how).
if you need something better I'd put that in a new issue, explaining what's the scenario.
